sudo: false
language: java
jdk: 
- oraclejdk8
install:
  - mvn clean install
script:
  - mvn test jacoco:report
after_success:
  - cd $TRAVIS_BUILD_DIR/target/generated-docs  ; mv README.html index.html ; cp -R ../doc doc
  - git init
  - git config --global  user.name "${GH_USER_NAME}"
  - git config --global  user.email "{GH_USER_EMAIL}"
  - git status
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git checkout -b gh-pages
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" gh-pages
